Update Doc
massalabs/massa-as-sdk pull request #119
Opened 2022-12-22 13:29 UTC by 0xMazout

2022-12-22 14:19 UTC, Thykof requested changes

2022-12-22 14:19 UTC, Thykof commented on assembly/std/context.ts
> + * local executions don’t change the stack: they allow executing foreign code in the current context.
```suggestion
 * local executions don’t change the stack, they allow executing foreign code in the current context.
```

2022-12-23 09:04 UTC, Thykof approved these changes

2022-12-23 09:17 UTC, gregLibert approved these changes

2022-12-23 09:18 UTC, merged