Transfer Event to index
massalabs/massa-as-sdk pull request #128
Opened 2023-01-02 16:29 UTC by 0xMazout

Transfer Event to index.

Need a refacto of index in the future

2023-01-02 16:40 UTC, SebastienValla approved these changes
LGTM !

2023-01-03 08:55 UTC, peterjah approved these changes

2023-01-03 08:59 UTC, 0xMazout commented
@Thykof Can you please merge it ? :)

2023-01-03 09:10 UTC, Thykof requested changes

2023-01-03 09:10 UTC, Thykof commented on assembly/std/index.ts
> + * @return {string} stringified event.
I am anticipating new typedoc rules

```suggestion
 * @param key - event key
 * @param args - array of string arguments.
 * @returns stringified event.
```

2023-01-03 09:11 UTC, Thykof approved these changes

2023-01-03 09:12 UTC, merged