update readme
massalabs/massa-as-sdk pull request #131
Opened 2023-01-04 16:14 UTC by SebastienValla

2023-01-04 16:17 UTC, Thykof requested changes
great!

2023-01-04 16:17 UTC, Thykof commented on README.md
> +- [`massa-as-sdk documentation`](https://massa.net)
```suggestion
- [`massa-as-sdk documentation`](http://as-sdk.docs.massa.net)
```

2023-01-04 16:17 UTC, Thykof commented on README.md
> +#Example
```suggestion
# Example
```

2023-01-04 16:17 UTC, Thykof commented on README.md
> +```sh
```suggestion
```sh
import { generateEvent } from '@massalabs/massa-as-sdk';
```

2023-01-05 08:40 UTC, Thykof approved these changes

2023-01-05 14:35 UTC, 0xMazout requested changes

2023-01-05 14:35 UTC, 0xMazout commented on README.md
```suggestion

_Massa Assemblyscript SDK_

```

2023-01-05 14:35 UTC, 0xMazout commented on README.md
> +- [`massa-as-sdk documentation`](http://as-sdk.docs.massa.net)
```suggestion
- [`massa-as-sdk documentation`](https://as-sdk.docs.massa.net)
```

2023-01-05 17:17 UTC, Thykof commented on README.md
> +
Text from the issue

```suggestion

SDK enables us to import object classes (such as address, storage objects) and use them without having to write all objects from scratch each time.

In order to call ABI functions, we import those functions in the smart-contract project, from the SDK dependency.
SDK is a set of tools, objects and functions, that are specific in usage only for Massa blockchain.

Contract standards (ERC-20, etc) have been removed from it.

```

2023-01-06 08:30 UTC, Thykof approved these changes

2023-01-06 14:20 UTC, longgamma-massa commented on README.md
> +SDK is a set of tools, objects and functions, that are specific in usage only for Massa blockchain.
it was a repetition from above

2023-01-06 14:21 UTC, longgamma-massa commented on README.md
> +Contract standards (ERC-20, etc) have been removed from it.
I'd remove this. We don't need to say in the documentation that we removed some parts. We will mention such things in the releases.

2023-01-06 14:21 UTC, longgamma-massa commented on README.md
> +Complete doc of all functions and object can be found here :
```suggestion
Complete documentation of all available functions and objects is here: 
```

2023-01-06 14:22 UTC, longgamma-massa commented on README.md
> +For instance here is a smart contract example generating an event "Hello World" on the blockchain
```suggestion
Here is a smart-contract example generating an event "Hello World" on the blockchain:
```

2023-01-06 14:28 UTC, longgamma-massa approved these changes

2023-01-06 14:36 UTC, Thykof approved these changes

2023-01-06 14:44 UTC, merged