Feature: Added mock context helpers functions
massalabs/massa-as-sdk pull request #243
Opened 2023-04-18 08:24 UTC by 0xSwapFeeder

2023-04-18 19:49 UTC, Ben-Rey commented on vm-mock/vm.js
> +        if (addrPtr == undefined || addrPtr == 0 || addrPtr == null) {
```suggestion
        if (!addrPtr) {
```

2023-04-19 07:51 UTC, Ben-Rey commented on assembly/vm-mock/env.ts
> + *   resetContext();
As I understand it should be mockNonAdminContext or maybe the function should be called resetContext()

2023-04-20 12:13 UTC, Ben-Rey requested changes

2023-04-20 12:13 UTC, Ben-Rey commented on vm-mock/vm.js
> +        console.log("contractAddress Before: " + contractAddress);
should we remove log ?

2023-04-20 12:38 UTC, 0xSwapFeeder commented on vm-mock/vm.js
> +        console.log("contractAddress Before: " + contractAddress);
absolutely !

2023-04-20 13:55 UTC, gregLibert approved these changes

2023-04-20 13:56 UTC, merged