fix(mock-storage): fixed missing exceptions and exceptions format
massalabs/massa-as-sdk pull request #254
Opened 2023-04-20 09:04 UTC by 0xSwapFeeder

Aim's to resolve #200 and #184.

2023-04-20 09:43 UTC, Ben-Rey commented on vm-mock/vm.js
> +            return addressStorage.get(k);
Here you don't use newArrayBuffer. It doesn't seem to affect the tests. Are you sure we don't need it ?

2023-04-20 09:43 UTC, Ben-Rey commented on vm-mock/vm.js
> +            return addressStorage.get(k);
same here

2023-04-20 12:29 UTC, Ben-Rey requested changes

2023-04-20 12:29 UTC, Ben-Rey commented on vm-mock/vm.js
>     * Check if the address prefix is valid
Just to trigger the review

2023-04-20 12:57 UTC, Ben-Rey approved these changes

2023-04-20 13:57 UTC, gregLibert approved these changes

2023-04-20 13:57 UTC, gregLibert commented
@0xSwapFeeder can you fix the conflict please and reassign this PR to me ?

2023-04-20 15:02 UTC, gregLibert requested changes
Fix conflict

2023-04-21 07:18 UTC, 0xSwapFeeder commented
> Fix conflict

Rebased branch on main :)

2023-04-21 09:27 UTC, gregLibert approved these changes

2023-04-21 09:28 UTC, merged