Replace gas price with fee
massalabs/massa-as-sdk pull request #30
Opened 2022-11-09 09:07 UTC by gterzian

Part of https://github.com/massalabs/massa/pull/3173

2022-11-09 11:14 UTC, Thykof requested changes

2022-11-09 11:14 UTC, Thykof commented on assembly/std/index.ts
> + rawFees,
You can use `npm run fmt` to format the code and see linting issues about jsdoc in order to make the CI green.

2022-11-10 08:47 UTC, Thykof approved these changes

2022-11-11 07:28 UTC, gterzian commented
Should we merge this? What is the procedure for that? @Thykof

2022-11-14 08:28 UTC, Thykof commented
@gterzian I am asking @gregLibert for review

2022-11-14 08:36 UTC, gregLibert approved these changes

2022-11-14 08:36 UTC, merged

2022-11-14 08:39 UTC, gregLibert commented
thanks @gterzian !

2022-11-14 19:08 UTC, qdrn commented
This change will only be effective in the testnet 17. This makes the latest version of massa-as-sdk not compatible with the current testnet (used for hackathon). Is that a problem ? @gregLibert @Thykof

2022-11-15 06:25 UTC, gregLibert commented
Yes it is. We need to reverse...

2022-11-15 08:27 UTC, gterzian commented
Ok, restored the branch and will re-open later when we can merge...