20 fungible token vote
massalabs/massa-as-sdk pull request #48
Opened 2022-11-16 17:41 UTC by 0xMazout

Adding : 

Cast Vote : To spend voting power on a proposal

CRUD Proposal : To manage proposal

Delegate : To Delegate our voting power

Storing datas : 
VotingData : Related to Voting Data proposal , 
Data : Related to Data proposal,
VotingData*ProposalID*AddrSpender* : Related to voting Data user on proposal
proposal : Related to all proposals created by the addr

2022-11-17 14:52 UTC, 0xMazout commented
There is package.json push to correct the bug we find on asprettier windows stuff

2022-11-17 15:10 UTC, 0xMazout commented
Currently creating some units tests but we can review the architecture  and the choice made

2022-11-18 10:11 UTC, SebastienValla requested changes

2022-11-18 10:11 UTC, SebastienValla commented on assembly/token/impl.ts
> +  const delegatedPowerRecipient = new Args(Storage.getOf(recipientAddress, 'DelegatedPower')).nextU64();
why use args in this case and not  u64(string) ?

2022-11-18 10:11 UTC, SebastienValla commented on assembly/token/impl.ts
> +    const title = argsproposal.nextString();
title is never used

2022-11-21 15:49 UTC, Thykof commented
fix #29

2022-12-08 10:04 UTC, Thykof commented
this will be done in https://github.com/massalabs/massa-sc-contracts/pull/12

2022-12-08 10:04 UTC, closed without merging