add timestamp function
massalabs/massa-as-sdk pull request #82
Opened 2022-11-28 15:08 UTC by SebastienValla

2022-11-28 15:32 UTC, Thykof approved these changes
LGTM

2022-11-29 14:58 UTC, 0xMazout approved these changes
Tested & Approved 👍

2022-11-29 15:41 UTC, gregLibert requested changes
:mag: you should handle the proper length of your returned arguments type yourself.

2022-11-29 15:41 UTC, gregLibert commented on astester.imports.js
> +        return BigInt(Date.now());
You should force the conversion to an u64 value yourself.

```suggestion
        return BigInt.asUintN(64, Date.now());  
```

2022-11-29 16:04 UTC, gregLibert approved these changes
:+1:

2022-11-29 16:05 UTC, merged